"""empty message

Revision ID: 7876299efc3a
Revises: 792be0f9c601
Create Date: 2018-11-09 22:45:37.758708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7876299efc3a'
down_revision = '792be0f9c601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aluno', 'data_hora_login',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)
    op.alter_column('aluno', 'data_hora_logoff',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)
    op.alter_column('aluno', 'uuid',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aluno', 'uuid',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('aluno', 'data_hora_logoff',
               existing_type=sa.VARCHAR(length=14),
               nullable=False)
    op.alter_column('aluno', 'data_hora_login',
               existing_type=sa.VARCHAR(length=14),
               nullable=False)
    # ### end Alembic commands ###
