"""empty message

Revision ID: 792be0f9c601
Revises: 
Create Date: 2018-11-09 22:32:46.201174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792be0f9c601'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('ra', sa.String(length=8), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('data_hora_login', sa.String(length=14), nullable=False),
    sa.Column('data_hora_logoff', sa.String(length=14), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('data_hora_login'),
    sa.UniqueConstraint('data_hora_logoff'),
    sa.UniqueConstraint('ra'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aluno')
    # ### end Alembic commands ###
